# Generated by Django 5.0.1 on 2024-01-19 08:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_follows_user_saved_posts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.create_profile_cover_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='no_pic.png', upload_to=account.models.create_profile_image_path),
        ),
    ]
