# Generated by Django 5.0.1 on 2024-01-19 09:54

import account.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_profile_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.create_profile_cover_path, validators=[
                utils.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='no_pic.png', upload_to=account.models.create_profile_image_path, validators=[
                utils.validators.validate_image]),
        ),
    ]
