# Generated by Django 5.0.1 on 2024-01-19 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profile_cover_and_more'),
        ('network', '0003_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_by', to='network.post'),
        ),
    ]
