# Generated by Django 5.0.1 on 2024-01-19 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_follows_alter_user_saved_posts'),
        ('network', '0005_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='network.post'),
        ),
    ]
