# Generated by Django 5.0.1 on 2024-01-26 16:41

import account.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(blank=True, default='no_cover.png', upload_to=account.models.create_profile_cover_path, validators=[utils.validators.validate_image]),
        ),
    ]
