# Generated by Django 5.0.1 on 2024-01-19 18:13

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(upload_to='posts/%Y/%m/%d', validators=[utils.validators.validate_image]),
        ),
    ]
