# Generated by Django 5.0.1 on 2024-01-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
