# Generated by Django 5.0.1 on 2024-01-29 13:28

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_content',
            field=models.FileField(blank=True, upload_to='posts/%Y/%m/%d', validators=[utils.validators.validate_video]),
        ),
    ]
